### ISSUE TITLE
After latest Discord update, "Lib Discord Internals v1.3 or higher not found" error on startup.

### ISSUE THREAD

**Issue by Pimpmuckl** [samogot/betterdiscord-plugins#12]
Just updated Discord and throws an error on startup, Quote functionality doesn't work anymore.

Error: https://i.imgur.com/v0wIi9B.png

**Comment by Icarus77** [comment]
I have the same error. I was just about to come here to report it.

**Comment by TheLovinator1** [comment]
["This is an issue with Samogot's library—not BetterDiscord itself. You will have to wait for him to update the library for a fix. The reason it broke is that discord restructured some of their internal data and the library is unable to hook onto it." - rauenzi](https://github.com/Jiiks/BetterDiscordApp/issues/574#issuecomment-334349554)
