### ISSUE TITLE
NoSendScroll lib error

### ISSUE THREAD

**Issue by GenesisAria** [samogot/betterdiscord-plugins#14]
I get the lib internals error after recent discord update no matter what i do. I have the lib js in, and it was working, but after a recent update it stopped working.

**Comment by Icarus77** [comment]
The update broke it and there's been plenty of threads on it before. For some reason the mod closes the threads because the reason was posted in a completely different GitHub page, instead of keeping the issues here for others to know.

**Comment by Fillzest** [comment]
will this bug fix?
