### ISSUE TITLE
LibDiscordInternals doesn't work anymore

### ISSUE THREAD

**Issue by MaxiHuHe04** [samogot/betterdiscord-plugins#15]
LibDiscordInternals doesn't work anymore with the latest Discord version and Quoter doesn't work too (And there is no error in the BetterDiscord log file)

**Comment by Inve1951** [comment]
quoter: <https://github.com/samogot/betterdiscord-plugins/pull/13>
lib: <https://github.com/samogot/betterdiscord-plugins/tree/react-16-fix>

**Comment by MaxiHuHe04** [comment]
Oh, thank you, I didn't see that
