### ISSUE TITLE
Quoter - Clicking quote closes discord window

### ISSUE THREAD

**Issue by arkenthera** [samogot/betterdiscord-plugins#17]
How on earth is that even possible? Quoting works but clicking the quote button closes the discord window. I am on Windows 10.

Demo: https://gfycat.com/gifs/detail/ParchedGorgeousBonobo

Plugins folder: https://i.imgur.com/4BAwfKE.png

Plugins UI: https://i.imgur.com/xFMR0o4.png

**Comment by intrnl** [comment]
Internal changes in Discord causes Quoter to be unable to find the object it needs.

**Comment by Inve1951** [comment]
the window gets hidden, not closed
click the tray icon to get it back until there's a fix

**Comment by arkenthera** [comment]
In current code, `ContextMenuActions.close()` will call `window.close()` which will close/hide the current window. Here is a work around that I am using which fixes this. Note that when you click the quote button, it wont close the context menu, it will hide it and next time you click somewhere on the screen then the context menu will be removed from DOM.

https://github.com/samogot/betterdiscord-plugins/compare/master...arkenthera:master

**Comment by Inve1951** [comment]
it was like that in the past but it has the side effect of textarea losing focus

**Comment by arkenthera** [comment]
Certainly better than losing the window itself!

**Comment by Inve1951** [comment]
not saying it isn't
