### ISSUE TITLE
Issue with quoting in a channel you can't post to

### ISSUE THREAD

**Issue by fhlox** [samogot/betterdiscord-plugins#2]
Due to my curiosity (and stupidity) I now have [this](http://puu.sh/wGVnA/9b4e262d44.png) stuck in a channel I can't post to. I can't backspace the text or get rid of it in any way I've tried. I can still use that to quote the announcement like I wanted, but I now can't remove it. Do you know a way to get rid of it?

**Comment by samogot** [comment]
There is temporary solution to get rid of it now: press Ctrl+Shift+I, paste this code there and press enter:
```JavaScript
jQuery('textarea').val('')
```

I'll fix it in next release

**Comment by fhlox** [comment]
Well.. it sorta worked, but the box didn't go back to it's usual 1 line height, seen [here.](https://u.nya.is/xfvdqy.png)

**Comment by noodlebox** [comment]
Try this instead: ```javascript
$('textarea').val('')[0].dispatchEvent(new Event('input', { bubbles: true }));
```

**Comment by fhlox** [comment]
Actually, I was mistaken. I just had to change channels and back.

**Comment by samogot** [comment]
try quoter 3.4. should be fixed
