### ISSUE TITLE
Quoter will not run despite being on latest version

### ISSUE THREAD

**Issue by ElectronicWizard** [samogot/betterdiscord-plugins#29]
I have the quoter and libdiscordinternal files from readme.md. Not really sure what else to put here.

Latest version of Discord Desktop App on Windows 10 1709 Edu.

**Comment by m3037** [comment]
Can confirm. I'm on OS X 10.9.5, BetterDiscord v0.2.82, and I have the latest quoter and 1lib_discord_internals. Upon opening Discord, there's no option to quote in the context menu, or on the right side of messages. Pressing ctrl+shift+c doesn't work either. If I reload the discord client with command+r, the quoter works sometimes, but it seems unstable.

**Comment by KaKi87** [comment]
+1

**Comment by rauenzi** [comment]
Commenting "+1" doesn't help anyone and only serves to send us unnecessary notifications.

For those with issues, make sure you have the latest of each since there was a hotfixes the other day. If the buttons don't show up, then go to the friends list and press `ctrl`+`r` that should allow the plugin to patch onto the Message object.

**Comment by KaKi87** [comment]
Commenting "+1" just means "I have the same problem".

But you're right, the latest version corrected the bug. Thanks !

**Comment by rauenzi** [comment]
You can also give a thumbs up reaction to the original comment as opposed to sending everyone notifications. 

It's best practice to always check your version before making or adding onto issues anyways.

**Comment by KaKi87** [comment]
Oh, I'm sorry, I didn't seen this button, I don't use GitHub very much.

**Comment by m3037** [comment]
I'm on the latest "hotfix" version from 2 days ago, and still there are no buttons for quoting and ctrl+shift+c doesn't do anything until I do ctrl+r to reload discord. Any ideas? If it helps, I'm on OS X, but have the same problem on linux.

**Comment by rauenzi** [comment]
As I said in a previous comment reloading while in friends list is currently the only workaround. You'll have to wait for a proper fix for that specific issue.

**Comment by SilverlightPony** [comment]
Quoter just stopped working for me after a comp restart.  The above mentioned fix/workaround did not help.

**Comment by samogot** [comment]
should be fixed by #33

**Comment by rauenzi** [comment]
I don't see any errors there, if you'd like for it to use embeds, you do so AT YOUR OWN RISK by checking the box in settings.

**Comment by KaKi87** [comment]
Oh okay
