### ISSUE TITLE
Embed format broken

### ISSUE THREAD

**Issue by datWeazel** [samogot/betterdiscord-plugins#35]
When quoting a message the markdown is broken.
Quotes are no longer shown as embedded messages. 

Example: https://i.imgur.com/I3Wyq4s.png

**Comment by Inve1951** [comment]
re-enable embeds in the plugin settings

**Comment by samogot** [comment]
I can't see what is broken in markdown markup. Emojis newer work in code blocks if it is the thing you are talking about. Markdown markup is default now, but you can switch it back to embed mode in settings

**Comment by datWeazel** [comment]
Yeah the "embeds option" was disabled in the settings and I din't know that. Sorry.
