### ISSUE TITLE
Quoter button/icon not displaying

### ISSUE THREAD

**Issue by SilverlightPony** [samogot/betterdiscord-plugins#37]
Noticed a few days ago that the Quoter button/icon had stopped appearing.  At first I thought Quoter had stopped working altogether, but later realized the plugin was still working aside from that icon.

Reinstalling both BandagedBD and Quoter had no effect.

**Comment by intrnl** [comment]
Duplicate of issue #36

**Comment by samogot** [comment]
Fixed with lib v1.11
