### ISSUE TITLE
Broken since latest patches.

### ISSUE THREAD

**Issue by Tancred423** [samogot/betterdiscord-plugins#38]
Hotkey, MB2->Quote or the Quote icon. All options just do nothing since the latest discord patch.
My discord version: (i dont find the number right now), but it's the stable version.
OS: win10pro
Other plugins: A few, but even on disabling them, Quoter still doesn't work.

**Comment by KaKi87** [comment]
![2018_08_07_17_34_55_developer_tools_https_discordapp com_channels_280806472928198656_28081787935-min](https://user-images.githubusercontent.com/21284089/43786219-6e9581c4-9a68-11e8-8eb1-b3a7c02cc1f2.png)

**Comment by Inve1951** [comment]
temporary fix by me: https://cdn.discordapp.com/attachments/327159647041748992/476023855257747456/quoter.plugin.js

expect official one by @rauenzi later today
