### ISSUE TITLE
Quoter won't start: Cannot invoke start()

### ISSUE THREAD

**Issue by SCBionicle** [samogot/betterdiscord-plugins#39]
I tried running quoter as I usually do but then after I turned on my computer today, an error message came up: `cannot invoke start()` or something like that. I tried reinstalling quoter with no luck, reinstalling discord internals with no luck, I even tried reinstalling Bandaged Discord it will still not work.

Every time I try turning on Quoter in the plugin settings, once I close out of the settings, the switch goes right back to off.

**Comment by kuplion** [comment]
Exactly the same here, it worked yesterday and fails today.

**Comment by SilverlightPony** [comment]
Same issue here.  It gave me that error once, and now refuses to turn on in settings>plugins.  Don't even have to close settings entirely for the switch to flip back off; just go to a different settings page.

Side-note: "full offline list" won't turn on either.

**Comment by JerryCMancuso** [comment]
Same issue here.
