### ISSUE TITLE
Latest Discord update has broken Quoter

### ISSUE THREAD

**Issue by bacevs** [samogot/betterdiscord-plugins#41]
Can no longer quote comments as the quotation marks no longer appear next to the messages you hover over anymore.
Note: Running on windows 10

**Comment by rauenzi** [comment]
This is known. Waiting to fix until discord stops messing with the module we need to patch. For now you can still right click a message to quote or use the keyboard shortcut

**Comment by Ownsin** [comment]
> This is known. Waiting to fix until discord stops messing with the module we need to patch. For now you can still right click a message to quote or use the keyboard shortcut

Right-clicking a message doesn't' work either.

**Comment by intrnl** [comment]
Tried reinstalling BD yet, @Ownsin?

**Comment by Ownsin** [comment]
> Tried reinstalling BD yet, @Ownsin?

I did and now It's working with the right clicking again, but I hope in the near future there will be an update so the button will reappear again instead of the right clicking.

Thank you for your help.

**Comment by KaKi87** [comment]
On my computer, the quote shortcut (Ctrl + Shift + C) only works if you refresh Discord (Ctrl + R) right before doing it.

**Comment by samogot** [comment]
fixed in v3.14
