### ISSUE TITLE
Full offline list is still broken

### ISSUE THREAD

**Issue by tryoutuser** [samogot/betterdiscord-plugins#45]
I saw there is a new push 8 days ago to the plugin and lib discord internals, I downloaded and replaced them recently, and the plugin itself still cannot start but lib internals can.
I really hope you will update the plugin soon, thank you for useful plugins you've made!

**Comment by samogot** [comment]
No, I wont. Unfortunately

This plugin is no longer supported, because it can't be fixed anymore. Now server feeds data to be displayed in members sidebar directly, and there is no way to influence on this.
