### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by MOP9I4OK** [samogot/betterdiscord-plugins#49]
Hi.
The plugin does not work

**Comment by zerebos** [comment]
Which plugin? What version are you using? Do you have the library, if so, what version? What does "not working" mean, is it not starting, or is the functionality not what you expected?

**Comment by MOP9I4OK** [comment]
The Quoter plugin is the v3.14 version of the plugin. at start writes could not be started I also have the library installed

**Comment by MOP9I4OK** [comment]
Do everything. 
Everything works for me now, I'm sorry.

**Comment by scsa20** [comment]
> Do everything.
> Everything works for me now, I'm sorry.

What do you mean by "do everything?" I'm having the same issue and "do everything" doesn't mean anything to me.

Quoter plugin 3.14
Have lib discord internals v1.12 installed and active
BD v0.3.0
BBD v0.2.7
Discord Release Channel: Stable
Discord Build Number: 33990

**Comment by zerebos** [comment]
Update the library.

**Comment by scsa20** [comment]
Eh, thought I did updated the library, was one of the first things I tired when I first gotten the error few days ago, and just now noticed that the library was updated itself few days ago itself so guess I didn't bothered checking for an update the next day or something ¯\_(ツ)_/¯

**Comment by zerebos** [comment]
There was an announcement in the server, current version is 1.13
