### ISSUE TITLE
Quoter by Samogot stopped working

### ISSUE THREAD

**Issue by Kimochii-x3** [samogot/betterdiscord-plugins#50]
Out of nowhere ever since yesterday or the day before that, the quoter stopped working, anytime i restart discord, reinstall it or w/e the plugin doesn't run nor does it start when I manually start it, also I got it from betterdocs.us now its nowhere to be found there.. what am I supposed  to do to make it work?
It does have its required library too

**Comment by zerebos** [comment]
Make sure library is up to date version 1.13

**Comment by Kimochii-x3** [comment]
Ah, just a small thing being the issue, I had no idea that I had to update the library as well when the plugin got updated, I though the library stays the same version, anyway thank you, I'll keep that in mind for the future
